#
# BTstack example 'hid_mouse_demo' for ESP32 port
#
# Generated by C:\Users\k_yos\esp\esp-idf\btstack\port\esp32
# On Tue Aug 31 22:52:36 2021

PROJECT_NAME := hid_mouse_demo

include $(IDF_PATH)/make/project.mk
